name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: []
softdepend: [Essentials, Jobs, ProtocolLib, Towny, VanishNoPacket, Vault, WorldEdit, WorldGuard]
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
commands:
  ###########################
  # Plugin Library Commands #
  ###########################
  flexhooks:
    description: 'View all registered hooks and their statuses'
    aliases: [hooks]
  flexmodules:
    description: 'Viewing a FlexPlugin implementation''s registered modules and their statuses'
    aliases: [modules]
  flexreload:
    description: 'Universal reload command for FlexPlugin implementations'
    aliases: []
  flexsave:
    description: 'Universal save command for FlexPlugin implementations'
    aliases: []

  #--------------------------------------------------------------------------------------------------------------------#

  ###########################
  #  Help Library Commands  #
  ###########################
  flexhelp:
    description: 'Universal help command for FlexPlugin implementations'
    aliases: []

  #--------------------------------------------------------------------------------------------------------------------#

  ###########################
  #      Misc Commands      #
  ###########################

  flexdebug:
    description: 'Runs a registered debug tests'
    aliases: [debug]

permissions:
  ##########
  # Groups #
  ##########

  flexcore.admin:
    default: op
    children:
      flexcore.debug: true
      flexcore.hooks: true
      flexcore.modules: true
      flexcore.reload: true
      flexcore.save: true

  flexcore.user:
    default: true
    children:
      flexcore.help: true

  #########
  # Nodes #
  #########

  flexcore.debug:
    description: 'Access to the debugging command.'
    default: false

  flexcore.help:
    description: 'Access to universal help command.'
    default: false

  flexcore.hooks:
    description: 'Access to hooks command.'
    default: false
  flexcore.modules:
    description: 'View FlexPlugin modules'
    default: false

  flexcore.reload:
    description: 'Access to universal reload command.'
    default: false
  flexcore.save:
    description: 'Access to universal save command.'
    default: false