load timeout: 100 # In ticks (20 ticks = 1 second)
modify join message: true # FlexCore modifies the way the player join message is sent. It shouldn't affect other plugins, but if it does, set this to false.
modify quit message: true # FlexCore modifies the way the player leave message is sent. It shouldn't affect other plugins, but if it does, set this to false.
auto unload interval: 5 # In minutes, auto unloads offline players
player join:
  unloaded message: 'Unable to load your data.\nPlease try again.'
  message order:
  - first.message$identifier
  - second.message$identifier