general config:
  page items: 8
  line length: 54
messages:
  next page: '&c&oType &6&o/{COMMAND} {NEXTPAGE}[cmd:/{COMMAND} {NEXTPAGE}](txt:&aClick to go to the next page) &c&oto view the next page.'
  no elements: '&c&oNothing here.'
formats:
  headers:
    page:
      left side:
        prefix: '&8&m'
        text: '-'
        suffix: '&r'
      right side:
        prefix: '&8&m'
        text: '-'
        suffix: ''
      center: '&a{KEY} &c(pg.{PAGE}/{MAXPAGES})'
    page_subtitle:
      left side:
        prefix: '&8&m'
        text: '-'
        suffix: '&r'
      right side:
        prefix: '&8&m'
        text: '-'
        suffix: ''
      center: '&a{KEY}: &6{VALUE} &c(pg.{PAGE}/{MAXPAGES})'
    title:
      left side:
        prefix: '&8&m'
        text: '-'
        suffix: '&r'
      right side:
        prefix: '&8&m'
        text: '-'
        suffix: ''
      center: '&a{KEY}'
    subtitle:
      left side:
        prefix: '&8&m'
        text: '-'
        suffix: '&r'
      right side:
        prefix: '&8&m'
        text: '-'
        suffix: ''
      center: '&a{KEY}: &6{VALUE}'
    help:
      left side:
        prefix: '&8&m'
        text: '-'
        suffix: '&r'
      right side:
        prefix: '&8&m'
        text: '-'
        suffix: ''
      center: '&aHelp: &6{KEY} &c(pg.{PAGE}/{MAXPAGES})'
  elements:
    command: '&c/&4{LABEL}(txt:&6Aliases: &e{ALIASES})&c{COMMAND} &8- &e{DESCRIPTION}'
    element: '&6{KEY}'
    lib_plugin_module: '&e{NAME}&8 &8({STATUS}&8): &6{DESCRIPTION}'
    number: '&e{INDEX}) &6{KEY}'
    parties_party: '&e{INDEX}) &6{NAME} &8- &6{MEMBERS} member{S} &8- {LEADER}'
    title: '&e{KEY}: &6{VALUE}'